.TH SCM 1 scm\-VERSION
.SH NAME
scm \- simple clipboard manager
.SH SYNOPSIS
.B scm
.RB [ \-d\ directory]\ [\-v]\ [\-k]
.SH DESCRIPTION
scm is a minimalistic clipboard manager daemon for X.
.SH OPTIONS
.TP
.B \-v
prints version information to stderr, then exits.
.TP
.B \-d
sets the cache directory where all entries will be stored.
.TP
.B \-V
prints debug messages to stdout.
.TP
.B \-k
prevents old entires from being deleted.
.SH USAGE
Set the working directory for
.B scm
using the
.B \-d
flag.
.P
scm comes with a script,
.B scmenu,
which is a
.B dmenu(1)
wrapper that lets the user copy any of the stored entries
in to their clipboard.
.SH CUSTOMIZATION
Although it may not be necessary for all users, scm can be configured
by editing the config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SEE ALSO
.BR dmenu (1)
