#!/bin/sh -e
fail() { >&2 echo "${0##*/}: $@"; exit 1; }

LINE_CACHE="${LINE_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/scm/line_cache}"
test ! -f "$LINE_CACHE" && fail "cache file not found ($LINE_CACHE)"
echo $LINE_CACHE

input="$(cut -f2- "$LINE_CACHE" | dmenu -l 5 $*)"
test -z "$input" && fail "no input provided"

entry="$(grep -F -- "$input" "$LINE_CACHE" | cut -f1 | sed 1q)"
test -z "$entry" && fail "missing data"
xclip -selection clipboard <"$entry"
