#!/bin/sh -e
line_cache="${XDG_CACHE_HOME:-$HOME/.cache}/scm/line_cache"
if test ! -f "$line_cache"; then
	>&2 printf "error: cache file '%s' not found!\n" "$line_cache"
	exit 1
fi

input="$(cut -f2- $line_cache | dmenu -l 5 )"
if test -z "$input"
then
	return 1
fi
entry="$(grep -F "$input" "$line_cache" | cut -f1 | sed 1q)"
xclip -selection clipboard <"$entry"
